2016-02-23 06:21:12 Error: [MissingControllerException] Controller class PluginsController could not be found.
Exception Attributes: array (
  'class' => 'PluginsController',
  'plugin' => NULL,
)
Request URL: /intranet/plugins/misc/touch-punch/jquery.ui.touch-punch.min.js
Stack Trace:
#0 D:\Server\htdocs\intranet\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2016-02-23 06:21:12 Error: [MissingControllerException] Controller class PluginsController could not be found.
Exception Attributes: array (
  'class' => 'PluginsController',
  'plugin' => NULL,
)
Request URL: /intranet/plugins/misc/ios-fix/ios-orientationchange-fix.js
Stack Trace:
#0 D:\Server\htdocs\intranet\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2016-02-23 07:02:24 Error: Fatal Error (1): Call to a member function save() on a non-object in [D:\Server\htdocs\intranet\app\Controller\TransactionsController.php, line 142]
2016-02-23 07:02:24 Error: [FatalErrorException] Call to a member function save() on a non-object
Request URL: /intranet/transactions/edit_customer_data/3
Stack Trace:
#0 D:\Server\htdocs\intranet\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\\Server\\htdoc...', 142)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\\Server\\htdoc...', 142, Array)
#2 D:\Server\htdocs\intranet\lib\Cake\Core\App.php(933): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\\Server\\htdoc...', 142, Array)
#3 D:\Server\htdocs\intranet\lib\Cake\Core\App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-02-23 07:03:07 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'forwarded_by' cannot be null
Request URL: /intranet/transactions/edit_customer_data/3
Stack Trace:
#0 D:\Server\htdocs\intranet\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 D:\Server\htdocs\intranet\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('INSERT INTO `to...', Array)
#2 D:\Server\htdocs\intranet\lib\Cake\Model\Datasource\DboSource.php(1012): DboSource->execute('INSERT INTO `to...')
#3 D:\Server\htdocs\intranet\lib\Cake\Model\Model.php(1928): DboSource->create(Object(Track), Array, Array)
#4 D:\Server\htdocs\intranet\lib\Cake\Model\Model.php(1751): Model->_doSave(Array, Array)
#5 D:\Server\htdocs\intranet\app\Controller\TransactionsController.php(161): Model->save(Array)
#6 [internal function]: TransactionsController->edit_customer_data('3')
#7 D:\Server\htdocs\intranet\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(TransactionsController), Array)
#8 D:\Server\htdocs\intranet\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#9 D:\Server\htdocs\intranet\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(TransactionsController), Object(CakeRequest))
#10 D:\Server\htdocs\intranet\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}
2016-02-23 07:08:46 Error: Fatal Error (1): Call to a member function user() on a non-object in [D:\Server\htdocs\intranet\app\Controller\TransactionsController.php, line 125]
2016-02-23 07:08:46 Error: [FatalErrorException] Call to a member function user() on a non-object
Request URL: /intranet/transactions/edit_customer_data/3
Stack Trace:
#0 D:\Server\htdocs\intranet\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\\Server\\htdoc...', 125)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\\Server\\htdoc...', 125, Array)
#2 D:\Server\htdocs\intranet\lib\Cake\Core\App.php(933): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\\Server\\htdoc...', 125, Array)
#3 D:\Server\htdocs\intranet\lib\Cake\Core\App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
