2016-02-20 17:14:39 Error: [MissingControllerException] Controller class UsersController could not be found.
Exception Attributes: array (
  'class' => 'UsersController',
  'plugin' => NULL,
)
Request URL: /intranet/users/login
Stack Trace:
#0 E:\Appxampp\htdocs\intranet\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2016-02-20 17:14:51 Error: [MissingControllerException] Controller class PluginsController could not be found.
Exception Attributes: array (
  'class' => 'PluginsController',
  'plugin' => NULL,
)
Request URL: /intranet/plugins/misc/ios-fix/ios-orientationchange-fix.js
Stack Trace:
#0 E:\Appxampp\htdocs\intranet\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2016-02-20 17:14:51 Error: [MissingControllerException] Controller class PluginsController could not be found.
Exception Attributes: array (
  'class' => 'PluginsController',
  'plugin' => NULL,
)
Request URL: /intranet/plugins/misc/touch-punch/jquery.ui.touch-punch.min.js
Stack Trace:
#0 E:\Appxampp\htdocs\intranet\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2016-02-20 18:43:19 Error: [MissingActionException] Action PaymentsController::individual_transaction() could not be found.
Exception Attributes: array (
  'controller' => 'PaymentsController',
  'action' => 'individual_transaction',
)
Request URL: /intranet/payments/individual_transaction
Stack Trace:
#0 E:\Appxampp\htdocs\intranet\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 E:\Appxampp\htdocs\intranet\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(PaymentsController), Object(CakeRequest))
#2 E:\Appxampp\htdocs\intranet\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2016-02-20 19:23:43 Error: [MissingActionException] Action PaymentsController::individual_transaction_by_cash() could not be found.
Exception Attributes: array (
  'controller' => 'PaymentsController',
  'action' => 'individual_transaction_by_cash',
)
Request URL: /intranet/payments/individual_transaction_by_cash
Stack Trace:
#0 E:\Appxampp\htdocs\intranet\lib\Cake\Routing\Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 E:\Appxampp\htdocs\intranet\lib\Cake\Routing\Dispatcher.php(167): Dispatcher->_invoke(Object(PaymentsController), Object(CakeRequest))
#2 E:\Appxampp\htdocs\intranet\app\webroot\index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2016-02-20 20:49:02 Error: Fatal Error (1): Call to a member function findById() on a non-object in [D:\xampp\htdocs\intranet\app\Controller\TransactionsController.php, line 136]
2016-02-20 20:49:02 Error: [FatalErrorException] Call to a member function findById() on a non-object
Request URL: /intranet/transactions/edit_customer_data/3
Stack Trace:
#0 D:\xampp\htdocs\intranet\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 136)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 136, Array)
#2 D:\xampp\htdocs\intranet\lib\Cake\Core\App.php(933): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 136, Array)
#3 D:\xampp\htdocs\intranet\lib\Cake\Core\App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2016-02-20 21:01:18 Error: Fatal Error (1): Call to a member function findById() on a non-object in [D:\xampp\htdocs\intranet\app\Controller\TransactionsController.php, line 136]
2016-02-20 21:01:18 Error: [FatalErrorException] Call to a member function findById() on a non-object
Request URL: /intranet/transactions/edit_customer_data/24
Stack Trace:
#0 D:\xampp\htdocs\intranet\lib\Cake\Error\ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 136)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 136, Array)
#2 D:\xampp\htdocs\intranet\lib\Cake\Core\App.php(933): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 136, Array)
#3 D:\xampp\htdocs\intranet\lib\Cake\Core\App.php(906): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
